### ISSUE TITLE
Exception AttributeError when using as_dataframe() method 

### ISSUE THREAD

**Issue by shafeneger** [ibmdbanalytics/ibmdbpy#13]
I am using `ibmdby`on IBM Data Science Experience and encountering a error message during the transformation to `pandas.DataFrame`.

When I execute the following code:
```
from ibmdbpy import IdaDataBase, IdaDataFrame
idadb_ID = IdaDataBase(
    dsn="DASHDB;Database=BLUDB;Hostname=" 
    + HOST
    + ";Port=50000;PROTOCOL=TCPIP;UID=" 
    + USER
    + ";PWD=" 
    + PASSWORD
)

ida_df_1 = IdaDataFrame(idadb_ID, TABLE_NAME)
data_df_1 = ida_df_1.as_dataframe()
```
I get an error message:
"Exception AttributeError: "Cursor instance has no attribute 'closed'" in <bound method Cursor.__del__ of <pypyodbc.Cursor instance at 0x7f29081feea8>> ignored"

**Comment by nicoleschoen** [comment]
Thanks for reporting this issue. 
It is fixed with ibmdbpy (0.1.3.post9). Please give it a try.
