### ISSUE TITLE
Does not cope with tables having same name in different schemas

### ISSUE THREAD

**Issue by ToreNotland** [ibmdbanalytics/ibmdbpy#24]
The DB2 on Cloud/DashDB instance have two schemas: SCHEMA1 and SCHEMA2.
Both schemas have a table called TABLE, and both tables have four columns.

When attempting to read one of the tables into a Pandas dataframe in DSX:
df = IdaDataFrame(idadb_dashdb, 'SCHEMA1.TABLE').as_dataframe()

I get this:
ProgrammingError: ('42S22', '[42S22] [IBM][CLI Driver][DB2/LINUXX8664]  SQL0206N  "XXXID" is not valid in the context where it is used.  SQLSTATE=42703\n')

By not converting the dataframe to Pandas:
df = IdaDataFrame(idadb_dashdb, 'SCHEMA1.TABLE'), 
and listing the column names:
print(df.columns)

I see the columns of **both** SCHEMA1.TABLE and SCHEMA2:TABLE.

When I try listing some content:
df.head()

I get this error message:

ValueError: Length mismatch: Expected axis has 4 elements, new values have 8 elements

**Comment by ToniBollinger** [comment]
Fixed with fix for issue 31.
