### ISSUE TITLE
cannot upload dataframe with _insert_into_database

### ISSUE THREAD

**Issue by smnpaulo** [ibmdbanalytics/ibmdbpy#25]
I'm trying to insert a simple 5k row dataframe into dashDB and my insert_into_database code throws this error:
df is <class 'pandas.core.frame.DataFrame'>
dbobject is 'TEST_TABLE'
<ipython-input-36-0f797f0f9bd2> in load_table(df, file)
      5     print(type(df))
      6     print(dbobject.split('.')[-1])
----> 7     idadb._insert_into_database(df, dbobject.split('.')[-1])
      8     #idadb.as_idadataframe()
      9     print('Data loaded into ' + dbobject + ' from ' + CONFIG[file]['name'])

/usr/local/src/conda3_runtime.v21/4.1.1/lib/python3.5/site-packages/ibmdbpy/base.py in _insert_into_database(self, dataframe, tablename, silent)
   1898         boolean_flaglist = []
   1899         for column in dataframe.columns:
-> 1900             if set(dataframe[column].unique()).issubset([True, False, 0, 1, np.nan]):
   1901                 boolean_flaglist.append(1)
   1902             else:

/gpfs/fs01/user/s79e-ff921c9bef27c8-c8f269334405/.local/lib/python3.5/site-packages/pandas/core/generic.py in __getattr__(self, name)
   3612             if name in self._info_axis:
   3613                 return self[name]
-> 3614             return object.__getattribute__(self, name)
   3615 
   3616     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'unique'

**Comment by ToniBollinger** [comment]
We did not succeed in reproducing the problem. Could you send us the DDL of TABLE_TABLE and some sample data for the data frame? Which version of ibmdbpy did you use? Thanks!

**Comment by smnpaulo** [comment]
**here's the DDL:** CREATE TABLE SIMONPAULO.TESTTAB
(
	INVOICE_REFERENCE_ID VARCHAR(36),
	SUPPLIER VARCHAR(95),
	LEDGER_ACCOUNT VARCHAR(216),
	SUPPLIER_INVOICE_NUMBER VARCHAR(44),
	NET_PAYMENT_AMOUNT_IN_USD VARCHAR(12),
	BUSINESS_UNIT VARCHAR(10),
	MATERIALS VARCHAR(99),
	MATERIAL_CATEGORY_SPEND_CATEGORY VARCHAR(51),
	INVOICE_DATE VARCHAR(12),
	PAYMENT_DATE VARCHAR(12),
	UNIT_OF_MEASURE VARCHAR(6),
	CONTRACT_LINE VARCHAR(2),
	SUPPLIER_ID VARCHAR(13),
	PAYMENT_TERMS VARCHAR(11),
	COST_CENTER_ID VARCHAR(11),
	PURCHASE_ORDERS VARCHAR(13),
	INVOICE_LINE_MEMO VARCHAR(2),
	AMOUNT_IN_DOCUMENT_CURRENCY VARCHAR(14),
	COMPANY_ID VARCHAR(15),
	POSTING_DATE VARCHAR(12),
	PROPOSED_GL VARCHAR(9),
	CURRENCY VARCHAR(5),
	PURCHASE_ORDER_LINE VARCHAR(1825),
	OMNICLASS VARCHAR(22),
	PROJECT VARCHAR(95),
	INVOICE_MEMO VARCHAR(285),
	QUANTITY VARCHAR(9)
)
ORGANIZE BY COLUMN;

**part of the dataframe**:
[TEST_SAMPLE.xlsx](https://github.com/ibmdbanalytics/ibmdbpy/files/1487414/TEST_SAMPLE.xlsx)

**I am using ibmdbpy 0.1.4**

**Comment by mineo** [comment]
With the following DDL:

```sql
CREATE TABLE BLUADMIN.TEST_TABLE
(
    INVOICE_REFERENCE_ID VARCHAR(36),
    SUPPLIER VARCHAR(95),
    LEDGER_ACCOUNT VARCHAR(216),
    SUPPLIER_INVOICE_NUMBER VARCHAR(44),
    NET_PAYMENT_AMOUNT_IN_USD VARCHAR(12),
    BUSINESS_UNIT VARCHAR(10),
    MATERIALS VARCHAR(99),
    MATERIAL_CATEGORY_SPEND_CATEGORY VARCHAR(51),
    INVOICE_DATE VARCHAR(12),
    PAYMENT_DATE VARCHAR(12),
    UNIT_OF_MEASURE VARCHAR(6),
    CONTRACT_LINE VARCHAR(2),
    SUPPLIER_ID VARCHAR(13),
    PAYMENT_TERMS VARCHAR(11),
    COST_CENTER_ID VARCHAR(11),
    PURCHASE_ORDERS VARCHAR(13),
    INVOICE_LINE_MEMO VARCHAR(2),
    AMOUNT_IN_DOCUMENT_CURRENCY VARCHAR(14),
    COMPANY_ID VARCHAR(15),
    POSTING_DATE VARCHAR(12),
    PROPOSED_GL VARCHAR(9),
    CURRENCY VARCHAR(5),
    PURCHASE_ORDER_LINE VARCHAR(1825),
    -- You're missing this line
    PURCHASE_ORDER_LINE_1 VARCHAR(1825), 
    OMNICLASS VARCHAR(22),
    PROJECT VARCHAR(95),
    INVOICE_MEMO VARCHAR(285),
    QUANTITY VARCHAR(9)
  )
ORGANIZE BY COLUMN;
```
and the following code:
```python
# coding: utf-8
from ibmdbpy import IdaDataBase
db = IdaDataBase(dsn='jdbc:db2://<some-dsn-here>', verbose=True)
import pandas as pd
df = pd.read_excel('/Users/<me>/Downloads/TEST_SAMPLE.xlsx')
dbobject = 'TEST_TABLE'
# Db2 column names can't contain periods, so just remap this
df['PURCHASE_ORDER_LINE_1'] = df['PURCHASE_ORDER_LINE.1']
del df['PURCHASE_ORDER_LINE.1']
db._insert_into_database(df, dbobject.split('.')[-1], silent=False)
```
everything works as expected with ibmdbpy 0.1.4.

**Comment by mineo** [comment]
Also note that `'PURCHASE_ORDER_LINE.1'` only exists because there are two `PURCHASE_ORDER_LINE` columns in the excel sheet.

**Comment by smnpaulo** [comment]
@mineo thank you!
