### ISSUE TITLE
Same table name in different schemas doesn't work for upload

### ISSUE THREAD

**Issue by daniielamir** [ibmdbanalytics/ibmdbpy#31]
Hi! I am using IBMDBPY and are now starting to experience issues with it. I have created two different users who own two different schemas in DB2, which works fine with ibmdbpy as long as you only need to read data from a table. As soon as I try to upload data it thinks that I've got double the amounts of columns. The table I have created in both schemas in the database is called 'TEST' and only contain one column, aslo called 'TEST'. Basically this below works fine and correct:

```python
tableName = "TEST"
dbconnection = "DASHDB;DATABASE=BLUDB;HOSTNAME=xxx;PORT=50000;PROTOCOL=TCPIP;UID=user1;PWD=xxx;"
idadb = IdaDataBase(dsn=dbconnection) # Establish connection to DB2
table_res = IdaDataFrame(idadb, tableName).as_dataframe()
print(table_res) # This prints the correct table with ONLY one column.
```

Gets the correct data from the correct table in the correct schema. But when I do this below it is throwing an error saying the number of columns don't match what exists in the database:

```python
d = {'TEST': ["HEJ"]}
df = pd.DataFrame(data=d)
tableName = "TEST"
dbconnection = "DASHDB;DATABASE=BLUDB;HOSTNAME=xxx;PORT=50000;PROTOCOL=TCPIP;UID=user1;PWD=xxx;"
idadb = IdaDataBase(dsn=dbconnection) # Establish connection to DB2
table_res = IdaDataFrame(idadb, tableName)
print(table_res.columns) # This prints 2, even though there is only one
IdaDataBase.append(idadb1, table_res, df) # Fails here with the error message: (Ida)DataFrames don't have the same number of columnsidadb1.commit() # Commit the changes to DB2
idadb.commit()
```

How can I solve this?

**Comment by ToniBollinger** [comment]
Hi, I did not succeed in reproducing your problem.
But I have some questions:
In your description you are using in both sections the same userid "user1". But shouldn't it be two different users?
If you would use 2 different users like "user1" and "user2" then the table accessed in the first section would be "USER1.TEST" and in the section.section "USER2.TEST". Could it be that the second  table "USER2.TEST" has two columns?
Thanks!

**Comment by ToreNotland** [comment]
This is the same issues that I have encountered and described here: https://github.com/ibmdbanalytics/ibmdbpy/issues/24

**Comment by ToniBollinger** [comment]
I finally could reproduce this problem and I am working on a ficx.

**Comment by ToniBollinger** [comment]
I have fixed the problem and uploaded the new version 0.1.5 of ibmdbpy to https://pypi.org/project/ibmdbpy/.
