### ISSUE TITLE
Can't access dashDB via ODBC

### ISSUE THREAD

**Issue by gadamc** [ibmdbanalytics/ibmdbpy#4]
I've installed the db2driver on my mac. It's in /Applications/dsdriver.  The following envars are set

DYLD_LIBRARY_PATH=/Applications/dsdriver/lib/icc:/Applications/dsdriver/lib:/...
PATH=/Applications/dsdriver/adm:/Applications/dsdriver/bin:/...
PYTHONPATH=/Applications/dsdriver/lib:/...  

I `source /Applications/dsdriver/db2profile` so all of the envars there are set.

But I can't connect:

    In [1]: from ibmdbpy.base import IdaDataBase

    In [2]: idadb = IdaDataBase(dsn="DRIVER={IBM DB2 ODBC DRIVER - IBMDBCL1};DATABASE=BLUDB;HOSTNAME=dashdb-enterprise-yp-xxxxxx.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;", uid="xxxxx", pwd="xxxxx")
    ---------------------------------------------------------------------------
    IdaDataBaseError                          Traceback (most recent call last)
    <ipython-input-2-9595a0c1eab7> in <module>()
    ----> 1 idadb = IdaDataBase(dsn="DRIVER={IBM DB2 ODBC DRIVER - IBMDBCL1};DATABASE=BLUDB;HOSTNAME=dashdb-enterprise-yp-xxxxxx.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;", uid="xxxxx", pwd="xxxxx")

    /Users/adamcox/Envs/setisignaldbserver/lib/python2.7/site-packages/ibmdbpy/base.pyc in __init__(self, dsn, uid, pwd, autocommit, verbose)
        176                 self._con = pypyodbc.connect(self._connection_string)
        177             except Exception as e:
    --> 178                 raise IdaDataBaseError(e.value[1])
        179 
        180         if self._con_type == 'jdbc':

    IdaDataBaseError: ibmdbpy::IdaDataBaseError: [IM012] [unixODBC][Driver Manager]DRIVER keyword syntax error
   

Any thoughts or help? 

Thanks. 
Adam Cox (IBMer)

**Comment by edouardfouche** [comment]
Hi Adam,
Thank you for your input.
We have never tested the connection via ODBC from a Mac/Linux.
However, JDBC works, you just need to install the jaydebeapi package and to put the jcc driver file in your CLASSPATH variable.  

I will have a look at it. Let me know in case you can have it work !

Best regards,
Edouard Fouché

**Comment by gadamc** [comment]
Hi...

Specifically, I'm hoping to get ibmdbpy working in a python runtime environment on bluemix. Do you know if this is possible?

**Comment by gadamc** [comment]
Yeah, I am aiming for ODBC because I don't think I can use JDBC on a python runtime environment on Bluemix. (Though I don't know for sure -- I presume that environment won't be able to run a .jar file).

**Comment by edouardfouche** [comment]
Ibmdbpy works on Bluemix using JDBC.
You may find these resources useful : 
https://github.com/ibmdbanalytics/ibmdbpy-notebooks
https://www.youtube.com/watch?v=tk9T1yPkn4c

**Comment by gadamc** [comment]
Sorry for the disappearing comments. 

I'm trying to use ibmdbpy in a python runtime in a cloud foundry app. Have you done that yet?

**Comment by edouardfouche** [comment]
No problem. This should work. 
The only problem is, how the JDBC driver is found in the environment.
The following line is a work around to download the driver and place it is the local ibmdbpy folder:
`!wget -O $HOME/.local/lib/python2.7/site-packages/ibmdbpy/db2jcc4.jar https://ibm.box.com/shared/static/lmhzyeslp1rqns04ue8dnhz2x7fb6nkc.zip`

But I think the problem you described is on your local Mac, not on CloudFoundry. Am I right?
