### ISSUE TITLE
0.1.5 version does not have fix for jdebeapi 1.1.1 version

### ISSUE THREAD

**Issue by marc-mclean1** [ibmdbanalytics/ibmdbpy#47]
This bug fix was committed prior to your 0.1.5 release.
[jaydebeapi 1.x.x compatibility fix](https://github.com/ibmdbanalytics/ibmdbpy/commit/5f165580bacd1c999219fa5d6264b5075b3435f7#diff-935270a8cf1b92a8cac8a15e0bdda120)
Commit ID: [5f16558](https://github.com/ibmdbanalytics/ibmdbpy/commit/5f165580bacd1c999219fa5d6264b5075b3435f7#diff-935270a8cf1b92a8cac8a15e0bdda120)

However, it never made it into the 0.1.5 release.  As a result, the IdaDataBase connection to a JDBC source does not work.

**Comment by marc-mclean1** [comment]
The fix is to pip install the latest code base from git.
For watson studio, my code looks like this:
`
!pip install git+https://github.com/ibmdbanalytics/ibmdbpy.git --ignore-installed --no-deps --upgrade
`

**Comment by marc-mclean1** [comment]
Also, it looks like the current version of ibmdbpy is still not finding my DB2 jars correctly.  To fix this, I had to add the jar explicitly to the classpath...

```
# Add db2jcc4.jar explicitly to the classpath.
cp = os.environ["CLASSPATH"]
if (cp.find("db2jcc4.jar") == -1):
    os.environ["CLASSPATH"] = os.environ["CLASSPATH"] + ":" + "/opt/ibm/connectors/db2/db2jcc4.jar"
    print(os.environ["CLASSPATH"])
```

**Comment by rolweber** [comment]
There's a release 0.1.6 on PyPI now, but no tag here in this repo to determine whether that fix is in.

**Comment by mineo** [comment]
I'm not sure what happened with 0.1.5, maybe @ToniBollinger knows. For now, use 0.1.6 or later.
