### ISSUE TITLE
model fitting does not handle other schemas than default schema

### ISSUE THREAD

**Issue by eva-feillet** [ibmdbanalytics/ibmdbpy#53]
**Example to reproduce the error:**
1 - connect to Db2 via ibmdbpy
2 - use sample data to train an association rules model on it
```python
import ibmdbpy.learn.association_rules as assoc
Assoc = assoc.AssociationRules(modelname="GOSALES.SHOPPING_RULES", minsupport=0.04, maxlen=4, maxheadlen=1, minconf=0.2)
print('Assoc successfully created')
Assoc.fit(orders, transaction_id="ORDER_NUMBER", item_id="PRODUCT_NUMBER", nametable = "PRODUCT_NAME_TYPE_LOOKUP", namecol='PRODUCT_NAME_TYPE', verbose=True)
```
3 - you should obtain an error message like this one:

> DatabaseError: com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-438, SQLSTATE=38A00, SQLERRMC=CDFAA0865E The model "BLUADMIN"."GOSALES.SHOPPING_RULES" does not exis, DRIVER=3.72.52

Although GOSALES.SHOPPING_RULES was successfully created, its schema is internally modified and reset to be the default schema (in my case BLUADMIN). Same issue arises at prediction step. To fix: enable handling of other schemas than the default schema in model fitting and prediction for the 3 ML classes of ibmdbpy.learn (KMeans, Assoc, Naïve Bayes)

**Comment by ToniBollinger** [comment]
This has been fixed with pull request  https://github.com/ibmdbanalytics/ibmdbpy/pull/56.
