### ISSUE TITLE
odbc connection hangs without any error when you are not connected to vpn

### ISSUE THREAD

**Issue by vinayreddy1983** [ibmdbanalytics/ibmdbpy#61]
I wasn't connected to vpn and was trying to use odbc apis (to reach an internal IBM server). Instead of returning an error message, pypyodbc.connect seems to hang.

**Comment by mineo** [comment]
If pypyodbc.connect hangs, please report that against the pypyodbc project.

**Comment by mineo** [comment]
Or set a connection timeout for pypyodbc: https://github.com/jiangwen365/pypyodbc/wiki/Setting-Time-Out
