### ISSUE TITLE
Release Tag for 0.1.6 ?

### ISSUE THREAD

**Issue by rolweber** [ibmdbanalytics/ibmdbpy#62]
A [version 0.1.6](https://pypi.org/project/ibmdbpy/0.1.6/) of ibmdbpy was published to PyPI on 2020-04-01. Could you please create a [release tag](https://github.com/ibmdbanalytics/ibmdbpy/releases) here in the repository, so that people coming here know from which commit that release was created?
I _guess_ it was https://github.com/ibmdbanalytics/ibmdbpy/commit/518183cb9758854c231953510e0fda983c584dfd by @ToniBollinger and @mineo.

**Comment by mineo** [comment]
I've added a tag for 0.1.6, but will not retroactively work through the other releases.

**Comment by rolweber** [comment]
thanks!
